### ISSUE TITLE
1.20.3 support [Feature request]

### ISSUE THREAD

**Issue by Themis3000** [ldtteam/DynView#44]
Currently trying to use this mod with fabric 1.20.3 creates the following error after the server loads:

```
[21:42:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: field_4573
        at com.dynview.Utils.TickTimeHandler.onServerTick(TickTimeHandler.java:37) ~[dynview-fabric-1.20.1-3.2.jar:?]
        at com.dynview.event.EventHandler.onDedicatedServerTick(EventHandler.java:14) ~[dynview-fabric-1.20.1-3.2.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.28+9468a19d3b-4449f2569c2e4df.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zfj000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:2434) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:874) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Thank you for your development of this mod, it allows me to make my server view distance huge without having to worry about lag if many players start to join. Just creating this issue so I can track on when a new version is released so I can get it installed again right when/if it releases.

**Comment by Thodor12** [comment]
~~This is a Forge mod, not a Fabric mod~~ Sorry, there's Fabric branches too, ignore me.

However this mod has not been ported over to 1.20.3 yet, it's only provided for 1.20 and 1.20.1
